import {Geist, Geist_Mono, Inter} from "next/font/google";
import "./globals.css";

const interSans = Inter({
   variable: "--font-inter-sans",
   subsets: ["cyrillic"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${interSans.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
